# Generated by Django 4.2.13 on 2024-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='challenge_burnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appuser',
            name='challenge_issued',
            field=models.BigIntegerField(default=0),
        ),
    ]
