# Generated by Django 4.2.13 on 2024-06-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_vote_backend', '0002_appuser_challenge_burnt_appuser_challenge_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='challenge_issued',
            field=models.CharField(max_length=50),
        ),
    ]
