# Generated by Django 4.2.13 on 2024-06-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_vote_backend', '0004_ballot'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballot',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
