# Generated by Django 4.2.13 on 2024-06-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_vote_backend', '0006_appuser_email_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='challenge_issued',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
