# Generated by Django 4.2.13 on 2024-06-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_vote_backend', '0007_alter_appuser_challenge_issued_alter_appuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
