# Generated by Django 4.2.13 on 2024-06-24 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_vote_backend', '0008_otp_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(default='')),
                ('ballot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections',
                                             to='e_vote_backend.ballot')),
            ],
        ),
    ]
