# Generated by Django 4.2.13 on 2024-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_vote_backend', '0010_alter_ballot_slug_alter_ballotsection_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ballotsection',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
