# Generated by Django 4.2.13 on 2024-06-26 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('e_vote_backend', '0011_alter_ballot_slug_alter_ballotsection_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BallotSectionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('option_id', models.IntegerField()),
                ('ballot_section',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options',
                                   to='e_vote_backend.ballotsection')),
            ],
        ),
    ]
